#!/bin/bash

source /opt/meta/global_functions
if [[ $? != 0 ]]; then
	$BDEBUG && echo "global_functions could not be sourced in"
	exit 1
fi

# $1 = geographical position of node (1-60)
node=$1

# The partent directory for individual node content
node_directory="/pxe/nodes/$(nodestring $node)"

# This pastes the first line in the last runfile to sed and deletes everything that is not a number
pid=$(head -1 "$node_directory/lastrun" | sed 's/[^0-9]//g')

echo $pid